- name: create ec2 and route 53
  hosts: local 
  connection: local
  vars:
   subnet_id: subnet-0633e41a33633242c
   sg_id: sg-0ad172ae2652efe40
   ami_id: ami-09c813fb71547fc4f
   instances:
    - mysql
    - backend
    - frontend
   zone: venuportal.online
  tasks:
    - name: create ec2 instance
      amazon.aws.ec2_instance:
       name: "{{ item }}"
       vpc_subnet_id: "{{subnet_id}}"
       instance_type: "t3.micro"
       security_group: "{{sg_id}}"
       image_id: "{{ami_id}}"
      loop: "{{instances}}"
      register: ec2_instances

    - name: read the output 
      ansible.builtin.debug:
       msg: "the output {{ ec2_instances }}"
    - name: created route53 using ip address
      ansible.aws.route53:
       name: crate route53 records
       state: present
       zone: "{{ zone }}"
       record: "{{item.item}}.{{ zone }}" # get the name for the dns ex musql.venuportal.online
       type: A 
       ttl: 1
       value: "{{ item.instances[0].private_ip_address #get the ip address from the reults }}"
       wait: true
       overwrite: true #if we have alredy records it will override 
      loop: "{{ ec2_instances.results }}"