- name: #using conditions
  hosts: [local]
  connection: local
  vars_prompt:
   - name: my_number
     prompt: enter the number #taken input from user
  tasks:
   - name: 
     ansible.builtin.debug:
      msg: "the given {{ my_number }} is less than 20 "
     when: my_number | my_number < 20

   - name: # second task
     ansible.builtin.debug:
      msg: "the given {{ my_number }} is greater than 20 "
     when: my_number | my_number > 20