- name: #using conditions check the user there are not
  hosts: [local]
  connection: local
  tasks:
   - name: #every usage may be we don't have ansible module so we use below command for the own command
     ansible.builtin.command: id expense
     register: user 
     ignore_errors: true

   - name: # print the user information
     ansible.builtin.debug:
      msg: " {{ user }}"
      
   - name: # crate user if not exists
     ansible.builtin.command: useradd expense
     when: user.rc != o
