-name: 
hosts: local
connection: local
 #become: yes # run with sudo access
tasks: 
  -name: 
   ansible.builtin.package:
    name: nginx
    state: present
   -name:
    ansible.builtin.service:
    name: nginx
    state: started