- name: #loops
  hosts: [local]
  connection: local
  tasks:
   - name: 
     ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
     loop:
       - { name: 'mysql' ,state: 'present'}

       - { name: 'nginx',state: 'absent' }

       - { name: 'postfix',state: 'present'}