- name: task level variables
  hosts: [local]
  connection: local
  vars:
   course: "devops"
   trainer: "siva"
   learner: "venugopal"
   topic: "ansible"
  tasks:
   - name:
     ansible.builtin.debug:
      msg: " iam {{ learner }} learning {{ course }} with {{ trainer }}"

   - name:
     vars:
       play: "task level"
       course: "ansible"
     ansible.builtin.debug:
      msg: " i am {{ learner }} learning the {{ play }} in {{ course }}"
    
   - name: # print the msg again again 
     ansible.builtin.debug:
      msg: "i am {{ learner}} laerning  the {{ course }}"